###
### Display
###
# Verbose program output
verbose = true

# Show progress
progress = true

###
### Exclusions
###
# Exclude URLs from checking (supports regex)
# does not exclude all github
exclude = [
  'https://sdk.launchdarkly.',
  'https://stream.launchdarkly.',
  'https://stream-tls10.launchdarkly.',
  'https://events.launchdarkly.',
  'https://events-tls10.launchdarkly.',
  'https://clientstream.launchdarkly.',
  'https://clientsdk.launchdarkly.',
  'https://app.launchdarkly.',
  'https://mobile.launchdarkly.',
  'https://console.aws.',
  'https://mockbin.org',
  'https://glitch.com',
  'https://app.logdna.com',
  'https://help.sleuth.io',
  'https://launchdarkly.service-now.com',
  'https://cocoapods.org',
  'https://www.makeuseof.com/tag/md5-hash-stuff-means-technology-explained/',
  'https://help.amplitude.com',
  'https://currentmillis.com',
  'https://support.launchdarkly.com',
  'https://support.pendo.io',
  'https://developers.cloudflare.com',
  'https://dash.cloudflare.com/*',
  # specific example links
  '^https://launchdarkly.github.io/$',
  # ignore git clone links
  'https://github.com/.+/.+.git',
  # links used in examples
  '.*domain.com',
  'https://base.custom_domain',
  'https://events.custom_domain',
  '.*your-domain.*',
  'http://example.*',
  'https://example.*',
  'https://api.example.*',
  'http://temp/variable',
  'http://my-consul:8100*',
  'http://my-relay-host.*',
  'http://my-relay-proxy.*',
  'https://your-relay-proxy.*',
  'http://my-proxy*',
  'https://my-proxy*',
  'https://static-domain*',
  'http://web-proxy.*',
  '(.)+proxy_host(.)+',
  'https://gitlab.com/\$%7BCI_PROJECT_PATH%7D/.*',
  'https://yourlinkhere.com',
  'https://.*.mycompany.launchdarkly.com',
  'https://.*.mycompany.launchdarkly.us',
  'https://unpkg.com',
  'https://cdn.jsdelivr.net',
  'https://launchdarklydemostack1-s3bucketforwebsitecontent-jffmp2434grq.s3.amazonaws.com/site/',
  'https://github.com/:organization/:repo/releases.atom',
  # This URL returns 404 in a browser, but holds an index.yaml and tar files,
  # and is what you should use as part of helm setup (/home/relay-proxy/deploying#using-helm-to-run-the-relay-proxy-in-kubernetes)
  'https://launchdarkly.github.io/ld-relay-helm',
  # Repeated 404s on these links - [Issue opened](https://github.com/lycheeverse/lychee/issues/431)
  'https://github.com/marketplace/actions/launchdarkly-code-references',
  'https://github.com/features/actions',
  'https://github.com/launchdarkly/dev',
  # TODO: SC-135999 workaround
  'https://www.php.net/manual/en/language.types.declarations.php',
  # TODO: SC-151435 workaround
  'https://www.npmjs.com/package/*',
  # TODO: SC-155104 workaround
  'https://mvnrepository.com/artifact/com.launchdarkly/*'
]

# Exclude all private IPs from checking
# Equivalent to setting `exclude_private`, `exclude_link_local`, and `exclude_loopback` to true
exclude_all_private = true

# Exclude all mail addresses from checking
exclude_mail = true
