name: Deploy to Staging
on:
  workflow_dispatch:
    inputs:
      PR_NUMBER:
        required: true
        description: The pull request number which triggered this workflow
    branches-ignore:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - '*-eap'

env:
  BUCKET_PREFIX: ${{ github.event.pull_request.number || github.event.inputs.PR_NUMBER || github.ref_name }}

jobs:
  build-deploy:
    if: ${{ github.event.pull_request.number != '' || github.event.inputs.PR_NUMBER != '' || endsWith(github.ref_name, '-eap') }}
    runs-on: ubuntu-latest
    name: Deploy to s3 staging
    permissions:
      id-token: write
      contents: read
      actions: write
    environment:
      name: staging
      url: http://docs-stg.launchdarkly.com/${{ env.BUCKET_PREFIX }}
    concurrency:
      group: staging-${{ github.event.pull_request.number || github.event.inputs.PR_NUMBER || github.ref_name }}
      cancel-in-progress: true
    uses: actions/checkout@v3
    uses: ./.github/workflows/build-deploy
    with:
      environment: staging

  smoke-test:
    needs: build-deploy
    runs-on: ubuntu-latest
    name: Smoke test staging
    uses: actions/checkout@v3
    uses: ./.github/workflows/smoke-test
    with:
      environment: staging
      
