name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Deploy to s3 production
    permissions:
      id-token: write
      contents: read
      actions: write
    environment:
      name: production
      url: https://docs.launchdarkly.com/
    concurrency: prod_deploys
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build-deploy
        with:
          environment: prod
          secret_github_token: ${{ secrets.GITHUB_TOKEN }}
          secret_gh_token: ${{ secrets.GH_TOKEN }}
          secret_algolia_admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          secret_gatsby_algolia_app_id: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          secret_gatsby_algolia_search_key: ${{ secrets.ALGOLIA_SEARCH_KEY }}
          secret_launchdarkly_client_side_id: ${{ secrets.PROD_LAUNCHDARKLY_CLIENT_SIDE_ID }}
          secret_gatsby_datadog_client_token: null
          secret_gatsby_datadog_rum_application_id: ${{ secrets.DATADOG_RUM_APPLICATION_ID }}
          secret_datadog_rum_client_token: ${{ secrets.DATADOG_RUM_CLIENT_TOKEN }}
          secret_track_js_token: ${{ secrets.TRACKJS_TOKEN }}
          secret_docs_deploybot_webhook_url: ${{ secrets.DOCS_DEPLOYBOT_WEBHOOK_URL }}
          aws_role_arn: ${{ vars.AWS_PROD_ROLE_ARN }}
          bucket_prefix: null
      - name: Notify slack
        if: failure()
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DOCS_DEPLOYBOT_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rotating_light::rotating_light::rotating_light::rocket: Docs site failed to deploy to *<https://docs.launchdarkly.com|Production>*. :rotating_light::rotating_light::rotating_light:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View failed run"
                    },
                    "action_id": "view-action-${{github.run_id}}",
                    "url": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "plain_text",
                      "text": ":github: Deploy triggered by ${{github.actor}}",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

        

  smoke-test:
    needs: build-deploy
    runs-on: ubuntu-latest
    name: Smoke test production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/smoke-test
        timeout-minutes: 10
        with:
          environment: prod
          secret_cypress_record_key: ${{ secrets.CYPRESS_RECORD_KEY }}
          secret_github_token: ${{ secrets.GITHUB_TOKEN }}
          secret_docs_deploybot_webhook_url: ${{ secrets.DOCS_DEPLOYBOT_WEBHOOK_URL }}
      - name: Notify slack
        if: failure()
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DOCS_DEPLOYBOT_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rotating_light::rotating_light::rotating_light::test_tube: Smoke tests failed on *<https://docs.launchdarkly.com|Production>* :rotating_light::rotating_light::rotating_light:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View failed run"
                    },
                    "action_id": "view-action-${{github.run_id}}",
                    "url": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "plain_text",
                      "text": ":github: Deploy triggered by ${{github.actor}}",
                      "emoji": true
                    }
                  ]
                }
              ]
            }