name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Deploy to s3 production
    permissions:
      id-token: write
      contents: read
      actions: write
    environment:
      name: production
      url: https://docs.launchdarkly.com/
    concurrency: prod_deploys
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build-deploy
        with:
          environment: prod

  smoke-test:
    needs: build-deploy
    runs-on: ubuntu-latest
    name: Smoke test production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/smoke-test
        with:
          environment: prod
    