name: Manually deploy to production
on: workflow_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Deploy to s3 production
    permissions:
      id-token: write
      contents: read
      actions: write
    environment:
      name: production
      url: https://docs.launchdarkly.com/
    concurrency: prod_deploys
    uses: actions/checkout@v3
    uses: ./.github/workflows/build-deploy
    with:
      environment: prod
      force_build: true

  smoke-test:
    needs: build-deploy
    runs-on: ubuntu-latest
    name: Smoke test production
    uses: actions/checkout@v3
    uses: ./.github/workflows/smoke-test
    with:
      environment: prod
    